### ISSUE TITLE
TAD-TAD interactions

### ISSUE THREAD

**Issue by jessakay** [hansiu/HiCEnterprise#5]
Thank you for sharing this great and easy-to-use tool! I was wondering if the test of significant domain-vs-domain interactions implemented in this package is similar in concept to the idea introduced for TAD cliques (as described [here](https://www.nature.com/articles/s41588-019-0392-0) and [here](https://doi.org/10.1101/2020.11.01.363903))? And if so, do you have some recommendations as to which statistical test tends to perform better for detecting such TAD-TAD interactions?

**Comment by barwil** [comment]
It seems that in the first paper the authors are using hypergeometric test to determine TAD-TAD interactions and then  proceed to do their clique-finding using networkx. This approach is supported by HiCEnterprise (i.e. hypergeometric test), however it does not control for the distance between potentially interacting TADs and is therefore enriched for closer (in chromosome distance) TAD-TAD interactions. We have also implemented Poisson tests for TAD-TAD interactions and I would recommend using it

**Comment by jessakay** [comment]
I see. I suppose their use of non-central hypergeometric distributions was aimed to address this as well.

Thank you for the quick explanation!
